// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUEbvJ9V7lRoDZU2k8Z7n1_tIpHYToRkc',
    appId: '1:806247951038:web:fbce465a4b9fd6f7dd8cef',
    messagingSenderId: '806247951038',
    projectId: 'farmerconnect-45f1a',
    authDomain: 'farmerconnect-45f1a.firebaseapp.com',
    storageBucket: 'farmerconnect-45f1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUfvx7DmUjjjBY31eYWJpTR2fpT4woQ_k',
    appId: '1:806247951038:android:3a77d840bcc54a7cdd8cef',
    messagingSenderId: '806247951038',
    projectId: 'farmerconnect-45f1a',
    storageBucket: 'farmerconnect-45f1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2qHiyTs63TrJxTfBQAeUIkLxv7U8spOw',
    appId: '1:806247951038:ios:2cce8ce0b8903cd3dd8cef',
    messagingSenderId: '806247951038',
    projectId: 'farmerconnect-45f1a',
    storageBucket: 'farmerconnect-45f1a.appspot.com',
    androidClientId: '806247951038-inrnqiodjrha3garvkvs6mao6bt4pjgi.apps.googleusercontent.com',
    iosClientId: '806247951038-1l01igak24l9mlgg5g7dnek8opnmhgcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2qHiyTs63TrJxTfBQAeUIkLxv7U8spOw',
    appId: '1:806247951038:ios:2cce8ce0b8903cd3dd8cef',
    messagingSenderId: '806247951038',
    projectId: 'farmerconnect-45f1a',
    storageBucket: 'farmerconnect-45f1a.appspot.com',
    androidClientId: '806247951038-inrnqiodjrha3garvkvs6mao6bt4pjgi.apps.googleusercontent.com',
    iosClientId: '806247951038-1l01igak24l9mlgg5g7dnek8opnmhgcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUEbvJ9V7lRoDZU2k8Z7n1_tIpHYToRkc',
    appId: '1:806247951038:web:080f7e71253645bcdd8cef',
    messagingSenderId: '806247951038',
    projectId: 'farmerconnect-45f1a',
    authDomain: 'farmerconnect-45f1a.firebaseapp.com',
    storageBucket: 'farmerconnect-45f1a.appspot.com',
  );
}
